# Generated by Django 3.0.6 on 2020-06-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Competitive', 'Competitive'), ('University', 'University'), ('Schools', 'Schools')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical')], max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookCategories')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.SubCategories')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('book_type', models.CharField(choices=[('used', 'used'), ('donated', 'donated')], max_length=200)),
                ('publication', models.CharField(max_length=50)),
                ('binding_cover', models.CharField(choices=[('paperback', 'paperback'), ('hardback', 'hardback')], max_length=200)),
                ('book_condition', models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('very_good', 'very good'), ('very_bad', 'very bad')], max_length=200)),
                ('subject', models.CharField(choices=[('Question_bank', 'Question bank'), ('Handbook', 'Handbook'), ('Worksheet', 'Worksheet')], max_length=200)),
                ('languages', models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('urdu', 'urdu'), ('marathi', 'marathi')], max_length=200)),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
