# Generated by Django 3.0.6 on 2020-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubcategories',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ManyToManyField(to='books.BookCategories'),
        ),
        migrations.AlterField(
            model_name='bookcategories',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('AIEEE', 'AIEEE'), ('NEET', 'NEET'), ('CAT', 'CAT'), ('PHYSICS', 'PHYSICS')], max_length=200),
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
        migrations.DeleteModel(
            name='SubSubCategories',
        ),
    ]
